TEST_MODE = False

TEST_START_BLOCK = 4
REAL_START_BLOCK = 1

if TEST_MODE:

    PREP_WARNING = 3
    PREP_END = 6

    LONG_WORK_BLOCK = 6
    SHORT_WORK_BLOCK = 6

    BREAK_WARNING = 3
    BREAK_END = 6

    SHORT_BREAK_WARNING_TIME = 10
    SHORT_BREAK_END_TIME = 5

    CATCHUP_REST_TIME = 5

    TARGET_STUDY_HOURS = 7

else:

    PREP_WARNING = 50 * 60
    PREP_END = 60 * 60

    LONG_WORK_BLOCK = 3 * 60 * 60
    SHORT_WORK_BLOCK = 2 * 60 * 60

    BREAK_WARNING = 10 * 60
    BREAK_END = 60 * 60

    SHORT_BREAK_WARNING_TIME = 10 * 60
    SHORT_BREAK_END_TIME = 5 * 60

    CATCHUP_REST_TIME = 15 * 60

    TARGET_STUDY_HOURS = 7